export default countryCodes = {
  AE: {name: 'United Arab Emirates', code: 'hold'},
  BA: {name: 'Bosnia & Herzegovina', code: 'hold'},
  BF: {name: 'Burkina Faso', code: 'hold'},
  BG: {name: 'Bulgaria', code: 'hold'},
  BI: {name: 'Burundi', code: 'hold'},
  BJ: {name: 'Benin', code: 'hold'},
  BN: {name: 'Brunei', code: 'hold'},
  BO: {name: 'Bolivia', code: 'hold'},
  BR: {name: 'Brazil', code: 'hold'},
  BT: {name: 'Bhutan', code: 'hold'},
  BW: {name: 'Botswana', code: 'hold'},
  CA: {name: 'Canada', code: 'hold'},
  CD: {name: 'Congo - Kinshasa', code: 'hold'},
  CF: {name: 'Central African Republic', code: 'hold'},
  CG: {name: 'Congo - Brazzaville', code: 'hold'},
  CH: {name: 'Switzerland', code: 'hold'},
  CI: {name: 'Côte d’Ivoire', code: 'hold'},
  CK: {name: 'Cook Islands', code: 'hold'},
  CL: {name: 'Chile', code: 'hold'},
  CM: {name: 'Cameroon', code: 'hold'},
  CO: {name: 'Colombia', code: 'hold'},
  CR: {name: 'Costa Rica', code: 'hold'},
  CU: {name: 'Cuba', code: 'hold'},
  CV: {name: 'Cape Verde', code: 'hold'},
  CY: {name: 'Cyprus', code: 'hold'},
  CZ: {name: 'Czechia', code: 'hold'},
  DE: {name: 'Germany', code: 'hold'},
  DJ: {name: 'Djibouti', code: 'hold'},
  DK: {name: 'Denmark', code: 'hold'},
  DM: {name: 'Dominica', code: 'hold'},
  DO: {name: 'Dominican Republic', code: 'hold'},
  EC: {name: 'Ecuador', code: 'hold'},
  EE: {name: 'Estonia', code: 'hold'},
  EG: {name: 'Egypt', code: 'hold'},
  ES: {name: 'Spain', code: 'hold'},
  ET: {name: 'Ethiopia', code: 'hold'},
  FI: {name: 'Finland', code: 'hold'},
  FJ: {name: 'Fiji', code: 'hold'},
  FM: {name: 'Micronesia', code: 'hold'},
  FR: {name: 'France', code: 'hold'},
  GA: {name: 'Gabon', code: 'hold'},
  GB: {name: 'United Kingdom', code: 'hold'},
  GE: {name: 'Georgia', code: 'hold'},
  GG: {name: 'Guernsey', code: 'hold'},
  GH: {name: 'Ghana', code: 'hold'},
  GI: {name: 'Gibraltar', code: 'hold'},
  GL: {name: 'Greenland', code: 'hold'},
  GM: {name: 'Gambia', code: 'hold'},
  GR: {name: 'Greece', code: 'hold'},
  GT: {name: 'Guatemala', code: 'hold'},
  GY: {name: 'Guyana', code: 'hold'},
  HK: {name: 'Hong Kong', code: 'hold'},
  HN: {name: 'Honduras', code: 'hold'},
  HR: {name: 'Croatia', code: 'hold'},
  HT: {name: 'Haiti', code: 'hold'},
  HU: {name: 'Hungary', code: 'hold'},
  ID: {name: 'Indonesia', code: 'hold'},
  IE: {name: 'Ireland', code: 'hold'},
  IL: {name: 'Israel', code: 'hold'},
  IM: {name: 'Isle of Man', code: 'hold'},
  IN: {name: 'India', code: 'hold'},
  IQ: {name: 'Iraq', code: 'hold'},
  IS: {name: 'Iceland', code: 'hold'},
  IT: {name: 'Italy', code: 'hold'},
  JE: {name: 'Jersey', code: 'hold'},
  JM: {name: 'Jamaica', code: 'hold'},
  JO: {name: 'Jordan', code: 'hold'},
  JP: {name: 'Japan', code: 'hold'},
  KE: {name: 'Kenya', code: 'hold'},
  KG: {name: 'Kyrgyzstan', code: 'hold'},
  KH: {name: 'Cambodia', code: 'hold'},
  KI: {name: 'Kiribati', code: 'hold'},
  KR: {name: 'South Korea', code: 'hold'},
  KW: {name: 'Kuwait', code: 'hold'},
  KZ: {name: 'Kazakhstan', code: 'hold'},
  LA: {name: 'Laos', code: 'hold'},
  LB: {name: 'Lebanon', code: 'hold'},
  LI: {name: 'Liechtenstein', code: 'hold'},
  LK: {name: 'Sri Lanka', code: 'hold'},
  LS: {name: 'Lesotho', code: 'hold'},
  LT: {name: 'Lithuania', code: 'hold'},
  LU: {name: 'Luxembourg', code: 'hold'},
  LV: {name: 'Latvia', code: 'hold'},
  LY: {name: 'Libya', code: 'hold'},
  MA: {name: 'Morocco', code: 'hold'},
  MD: {name: 'Moldova', code: 'hold'},
  ME: {name: 'Montenegro', code: 'hold'},
  MG: {name: 'Madagascar', code: 'hold'},
  MK: {name: 'North Macedonia', code: 'hold'},
  ML: {name: 'Mali', code: 'hold'},
  MM: {name: 'Myanmar (Burma)', code: 'hold'},
  MN: {name: 'Mongolia', code: 'hold'},
  MS: {name: 'Montserrat', code: 'hold'},
  MT: {name: 'Malta', code: 'hold'},
  MU: {name: 'Mauritius', code: 'hold'},
  MV: {name: 'Maldives', code: 'hold'},
  MW: {name: 'Malawi', code: 'hold'},
  MX: {name: 'Mexico', code: 'hold'},
  MY: {name: 'Malaysia', code: 'hold'},
  MZ: {name: 'Mozambique', code: 'hold'},
  NA: {name: 'Namibia', code: 'hold'},
  NE: {name: 'Niger', code: 'hold'},
  NG: {name: 'Nigeria', code: 'hold'},
  NI: {name: 'Nicaragua', code: 'hold'},
  NL: {name: 'Netherlands', code: 'hold'},
  NO: {name: 'Norway', code: 'hold'},
  NP: {name: 'Nepal', code: 'hold'},
  NR: {name: 'Nauru', code: 'hold'},
  NU: {name: 'Niue', code: 'hold'},
  NZ: {name: 'New Zealand', code: 'hold'},
  OM: {name: 'Oman', code: 'hold'},
  PA: {name: 'Panama', code: 'hold'},
AD: {name: 'Andorra', code: 'hold'},
AF: {name: 'Afghanistan', code: 'hold'},
AG: {name: 'Antigua & Barbuda', code: 'hold'},
AI: {name: 'Anguilla', code: 'hold'},
AL: {name: 'Albania', code: 'hold'},
AM: {name: 'Armenia', code: 'hold'},
AO: {name: 'Angola', code: 'hold'},
AR: {name: 'Argentina', code: 'hold'},
AS: {name: 'American Samoa', code: 'hold'},
AT: {name: 'Austria', code: 'hold'},
AU: {name: 'Australia', code: 'hold'},
AZ: {name: 'Azerbaijan', code: 'hold'},
BD: {name: 'Bangladesh', code: 'hold'},
BE: {name: 'Belgium', code: 'hold'},
BH: {name: 'Bahrain', code: 'hold'},
BS: {name: 'Bahamas', code: 'hold'},
BY: {name: 'Belarus', code: 'hold'},
BZ: {name: 'Belize', code: 'hold'},
DZ: {name: 'Algeria', code: 'hold'},
PE: {name: 'Peru', code: 'hold'},
PG: {name: 'Papua New Guinea', code: 'hold'},
PH: {name: 'Philippines', code: 'hold'},
PK: {name: 'Pakistan', code: 'hold'},
PL: {name: 'Poland', code: 'hold'},
PN: {name: 'Pitcairn Islands', code: 'hold'},
PR: {name: 'Puerto Rico', code: 'hold'},
PS: {name: 'Palestine', code: 'hold'},
PT: {name: 'Portugal', code: 'hold'},
PY: {name: 'Paraguay', code: 'hold'},
QA: {name: 'Qatar', code: 'hold'},
RO: {name: 'Romania', code: 'hold'},
RS: {name: 'Serbia', code: 'hold'},
RU: {name: 'Russia', code: 'hold'},
RW: {name: 'Rwanda', code: 'hold'},
SA: {name: 'Saudi Arabia', code: 'hold'},
SB: {name: 'Solomon Islands', code: 'hold'},
SC: {name: 'Seychelles', code: 'hold'},
SE: {name: 'Sweden', code: 'hold'},
SG: {name: 'Singapore', code: 'hold'},
SH: {name: 'St. Helena', code: 'hold'},
SI: {name: 'Slovenia', code: 'hold'},
SK: {name: 'Slovakia', code: 'hold'},
SL: {name: 'Sierra Leone', code: 'hold'},
SM: {name: 'San Marino', code: 'hold'},
SN: {name: 'Senegal', code: 'hold'},
SO: {name: 'Somalia', code: 'hold'},
SR: {name: 'Suriname', code: 'hold'},
ST: {name: 'São Tomé & Príncipe', code: 'hold'},
SV: {name: 'El Salvador', code: 'hold'},
TD: {name: 'Chad', code: 'hold'},
TG: {name: 'Togo', code: 'hold'},
TH: {name: 'Thailand', code: 'hold'},
TJ: {name: 'Tajikistan', code: 'hold'},
TL: {name: 'Timor-Leste', code: 'hold'},
TM: {name: 'Turkmenistan', code: 'hold'},
TN: {name: 'Tunisia', code: 'hold'},
TO: {name: 'Tonga', code: 'hold'},
TR: {name: 'Turkey', code: 'hold'},
TT: {name: 'Trinidad & Tobago', code: 'hold'},
TW: {name: 'Taiwan', code: 'hold'},
TZ: {name: 'Tanzania', code: 'hold'},
UA: {name: 'Ukraine', code: 'hold'},
UG: {name: 'Uganda', code: 'hold'},
US: {name: 'United States', code: 'hold'},
UY: {name: 'Uruguay', code: 'hold'},
UZ: {name: 'Uzbekistan', code: 'hold'},
VC: {name: 'St. Vincent & Grenadines', code: 'hold'},
VE: {name: 'Venezuela', code: 'hold'},
VG: {name: 'British Virgin Islands', code: 'hold'},
VI: {name: 'U.S. Virgin Islands', code: 'hold'},
VN: {name: 'Vietnam', code: 'hold'},
VU: {name: 'Vanuatu', code: 'hold'},
WS: {name: 'Samoa', code: 'hold'},
ZA: {name: 'South Africa', code: 'hold'},
ZM: {name: 'Zambia', code: 'hold'},
ZW: {name: 'Zimbabwe', code: 'hold'},
ZZ: {name: 'Current Region', code: 'hold'},
};
